package com.gamenight;

public enum GameType {
    WORKER_PLACEMENT,
    RESOURCE_CONTROL,
    DECK_BUILDER,
    AREA_CONTROL,
    COOPERATIVE,
    ASYMMETRICAL,
    COMBAT,
    HIDDEN_ROLES,
    PATTERN_BUILDING,
    DEDUCTION,
    DICE_ROLLING,
    NO_TYPE_DEFINED

}
